2023-03-21 22:43:42,308 INFO    StreamThr :24504 [internal.py:wandb_internal():88] W&B internal server running at pid: 24504, started at: 2023-03-21 22:43:42.307878
2023-03-21 22:43:42,309 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: status
2023-03-21 22:43:42,310 DEBUG   SenderThread:24504 [sender.py:send_request():317] send_request: status
2023-03-21 22:43:42,311 INFO    WriterThread:24504 [datastore.py:open_for_write():75] open: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_224336-3dt6rgmc\run-3dt6rgmc.wandb
2023-03-21 22:43:42,311 DEBUG   SenderThread:24504 [sender.py:send():303] send: header
2023-03-21 22:43:42,312 DEBUG   SenderThread:24504 [sender.py:send():303] send: run
2023-03-21 22:43:42,745 INFO    SenderThread:24504 [dir_watcher.py:__init__():216] watching files in: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_224336-3dt6rgmc\files
2023-03-21 22:43:42,745 INFO    SenderThread:24504 [sender.py:_start_run_threads():928] run started: 3dt6rgmc with start time 1679435021.31083
2023-03-21 22:43:42,745 DEBUG   SenderThread:24504 [sender.py:send():303] send: summary
2023-03-21 22:43:42,745 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: check_version
2023-03-21 22:43:42,746 INFO    SenderThread:24504 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2023-03-21 22:43:42,746 DEBUG   SenderThread:24504 [sender.py:send_request():317] send_request: check_version
2023-03-21 22:43:42,805 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: run_start
2023-03-21 22:43:42,809 DEBUG   HandlerThread:24504 [meta.py:__init__():34] meta init
2023-03-21 22:43:42,809 DEBUG   HandlerThread:24504 [meta.py:__init__():49] meta init done
2023-03-21 22:43:42,809 DEBUG   HandlerThread:24504 [meta.py:probe():215] probe
2023-03-21 22:43:42,810 DEBUG   HandlerThread:24504 [git.py:repo():40] git repository is invalid
2023-03-21 22:43:42,810 DEBUG   HandlerThread:24504 [meta.py:_save_pip():53] save pip
2023-03-21 22:43:42,819 DEBUG   HandlerThread:24504 [meta.py:_save_pip():67] save pip done
2023-03-21 22:43:42,819 DEBUG   HandlerThread:24504 [meta.py:probe():253] probe done
2023-03-21 22:43:42,821 DEBUG   SenderThread:24504 [sender.py:send():303] send: files
2023-03-21 22:43:42,821 INFO    SenderThread:24504 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2023-03-21 22:43:42,837 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: stop_status
2023-03-21 22:43:42,837 DEBUG   SenderThread:24504 [sender.py:send_request():317] send_request: stop_status
2023-03-21 22:43:43,063 DEBUG   SenderThread:24504 [sender.py:send():303] send: telemetry
2023-03-21 22:43:43,457 INFO    Thread-40 :24504 [upload_job.py:push():143] Uploaded file C:\Users\chris\AppData\Local\Temp\tmpo4a5t9wuwandb\3tltdatg-wandb-metadata.json
2023-03-21 22:43:43,752 INFO    Thread-36 :24504 [dir_watcher.py:_on_file_created():275] file/dir created: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_224336-3dt6rgmc\files\requirements.txt
2023-03-21 22:43:43,753 INFO    Thread-36 :24504 [dir_watcher.py:_on_file_created():275] file/dir created: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_224336-3dt6rgmc\files\output.log
2023-03-21 22:43:43,753 INFO    Thread-36 :24504 [dir_watcher.py:_on_file_created():275] file/dir created: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_224336-3dt6rgmc\files\wandb-metadata.json
2023-03-21 22:43:43,753 INFO    Thread-36 :24504 [dir_watcher.py:_on_file_created():275] file/dir created: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_224336-3dt6rgmc\files\wandb-summary.json
2023-03-21 22:43:44,337 DEBUG   SenderThread:24504 [sender.py:send():303] send: config
2023-03-21 22:43:44,338 DEBUG   SenderThread:24504 [sender.py:send():303] send: metric
2023-03-21 22:43:44,338 DEBUG   SenderThread:24504 [sender.py:send():303] send: telemetry
2023-03-21 22:43:44,339 DEBUG   SenderThread:24504 [sender.py:send():303] send: metric
2023-03-21 22:43:44,339 WARNING SenderThread:24504 [sender.py:send_metric():1127] Seen metric with glob (shouldn't happen)
2023-03-21 22:43:45,765 INFO    Thread-36 :24504 [dir_watcher.py:_on_file_modified():292] file/dir modified: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_224336-3dt6rgmc\files\output.log
2023-03-21 22:43:58,073 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: stop_status
2023-03-21 22:43:58,073 DEBUG   SenderThread:24504 [sender.py:send_request():317] send_request: stop_status
2023-03-21 22:44:12,530 ERROR   SenderThread:24504 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 22:44:12,531 ERROR   SenderThread:24504 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/3dt6rgmc was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 22:44:13,286 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: stop_status
2023-03-21 22:44:13,999 ERROR   SenderThread:24504 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 22:44:13,999 ERROR   SenderThread:24504 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/3dt6rgmc was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 22:44:16,392 ERROR   SenderThread:24504 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 22:44:16,392 ERROR   SenderThread:24504 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/3dt6rgmc was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 22:44:16,392 ERROR   SenderThread:24504 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\internal\internal_api.py", line 213, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 39, in execute
    request.raise_for_status()
  File "c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-03-21 22:44:20,697 ERROR   SenderThread:24504 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 22:44:20,697 ERROR   SenderThread:24504 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/3dt6rgmc was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 22:44:29,117 ERROR   SenderThread:24504 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 22:44:29,117 ERROR   SenderThread:24504 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/3dt6rgmc was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 22:44:33,297 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: stop_status
2023-03-21 22:44:45,818 ERROR   SenderThread:24504 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 22:44:45,819 ERROR   SenderThread:24504 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/3dt6rgmc was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 22:44:52,945 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: poll_exit
2023-03-21 22:44:57,997 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: keepalive
2023-03-21 22:45:03,048 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: keepalive
2023-03-21 22:45:08,106 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: keepalive
2023-03-21 22:45:13,142 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: keepalive
2023-03-21 22:45:18,172 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: keepalive
2023-03-21 22:45:23,193 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: keepalive
2023-03-21 22:45:24,773 ERROR   SenderThread:24504 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 22:45:24,774 ERROR   SenderThread:24504 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/3dt6rgmc was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 22:45:28,232 DEBUG   HandlerThread:24504 [handler.py:handle_request():138] handle_request: keepalive
