2023-03-21 23:38:57,144 INFO    StreamThr :8544 [internal.py:wandb_internal():88] W&B internal server running at pid: 8544, started at: 2023-03-21 23:38:57.143580
2023-03-21 23:38:57,145 DEBUG   HandlerThread:8544 [handler.py:handle_request():138] handle_request: status
2023-03-21 23:38:57,152 DEBUG   SenderThread:8544 [sender.py:send_request():317] send_request: status
2023-03-21 23:38:57,154 DEBUG   SenderThread:8544 [sender.py:send():303] send: header
2023-03-21 23:38:57,154 INFO    WriterThread:8544 [datastore.py:open_for_write():75] open: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_233857-1t3e085e\run-1t3e085e.wandb
2023-03-21 23:38:57,155 DEBUG   SenderThread:8544 [sender.py:send():303] send: run
2023-03-21 23:38:57,569 DEBUG   HandlerThread:8544 [handler.py:handle_request():138] handle_request: check_version
2023-03-21 23:38:57,575 INFO    SenderThread:8544 [dir_watcher.py:__init__():216] watching files in: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_233857-1t3e085e\files
2023-03-21 23:38:57,575 INFO    SenderThread:8544 [sender.py:_start_run_threads():928] run started: 1t3e085e with start time 1679438337.135579
2023-03-21 23:38:57,575 DEBUG   SenderThread:8544 [sender.py:send():303] send: summary
2023-03-21 23:38:57,575 INFO    SenderThread:8544 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2023-03-21 23:38:57,576 DEBUG   SenderThread:8544 [sender.py:send_request():317] send_request: check_version
2023-03-21 23:38:57,642 DEBUG   HandlerThread:8544 [handler.py:handle_request():138] handle_request: run_start
2023-03-21 23:38:57,655 DEBUG   HandlerThread:8544 [meta.py:__init__():34] meta init
2023-03-21 23:38:57,655 DEBUG   HandlerThread:8544 [meta.py:__init__():49] meta init done
2023-03-21 23:38:57,655 DEBUG   HandlerThread:8544 [meta.py:probe():215] probe
2023-03-21 23:38:57,671 DEBUG   HandlerThread:8544 [git.py:repo():40] git repository is invalid
2023-03-21 23:38:57,671 DEBUG   HandlerThread:8544 [meta.py:_save_pip():53] save pip
2023-03-21 23:38:57,672 DEBUG   HandlerThread:8544 [meta.py:_save_pip():67] save pip done
2023-03-21 23:38:57,672 DEBUG   HandlerThread:8544 [meta.py:probe():253] probe done
2023-03-21 23:38:57,690 DEBUG   SenderThread:8544 [sender.py:send():303] send: files
2023-03-21 23:38:57,691 INFO    SenderThread:8544 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2023-03-21 23:38:57,700 DEBUG   HandlerThread:8544 [handler.py:handle_request():138] handle_request: stop_status
2023-03-21 23:38:57,700 DEBUG   SenderThread:8544 [sender.py:send_request():317] send_request: stop_status
2023-03-21 23:38:57,881 DEBUG   SenderThread:8544 [sender.py:send():303] send: telemetry
2023-03-21 23:38:58,285 INFO    Thread-21 :8544 [upload_job.py:push():143] Uploaded file C:\Users\chris\AppData\Local\Temp\tmp1e5e6tiewandb\3a6bs35g-wandb-metadata.json
2023-03-21 23:38:58,592 INFO    Thread-17 :8544 [dir_watcher.py:_on_file_created():275] file/dir created: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_233857-1t3e085e\files\wandb-summary.json
2023-03-21 23:38:58,593 INFO    Thread-17 :8544 [dir_watcher.py:_on_file_created():275] file/dir created: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_233857-1t3e085e\files\output.log
2023-03-21 23:38:58,593 INFO    Thread-17 :8544 [dir_watcher.py:_on_file_created():275] file/dir created: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_233857-1t3e085e\files\requirements.txt
2023-03-21 23:38:58,593 INFO    Thread-17 :8544 [dir_watcher.py:_on_file_created():275] file/dir created: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_233857-1t3e085e\files\wandb-metadata.json
2023-03-21 23:39:00,598 INFO    Thread-17 :8544 [dir_watcher.py:_on_file_modified():292] file/dir modified: c:\Users\chris\OneDrive\Skrivebord\huggingFace\wandb\run-20230321_233857-1t3e085e\files\output.log
2023-03-21 23:39:06,619 DEBUG   HandlerThread:8544 [handler.py:handle_request():138] handle_request: pause
2023-03-21 23:39:06,619 INFO    HandlerThread:8544 [handler.py:handle_request_pause():696] stopping system metrics thread
2023-03-21 23:39:06,659 DEBUG   SenderThread:8544 [sender.py:send():303] send: stats
2023-03-21 23:39:12,898 DEBUG   HandlerThread:8544 [handler.py:handle_request():138] handle_request: stop_status
2023-03-21 23:39:12,898 DEBUG   SenderThread:8544 [sender.py:send_request():317] send_request: stop_status
2023-03-21 23:39:27,358 ERROR   SenderThread:8544 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 23:39:27,358 ERROR   SenderThread:8544 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/1t3e085e was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 23:39:28,108 DEBUG   HandlerThread:8544 [handler.py:handle_request():138] handle_request: stop_status
2023-03-21 23:39:28,715 ERROR   SenderThread:8544 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 23:39:28,715 ERROR   SenderThread:8544 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/1t3e085e was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 23:39:30,963 ERROR   SenderThread:8544 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 23:39:30,963 ERROR   SenderThread:8544 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/1t3e085e was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 23:39:30,963 ERROR   SenderThread:8544 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\internal\internal_api.py", line 213, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 39, in execute
    request.raise_for_status()
  File "c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-03-21 23:39:36,058 ERROR   SenderThread:8544 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 23:39:36,058 ERROR   SenderThread:8544 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/1t3e085e was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 23:39:44,530 ERROR   SenderThread:8544 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 23:39:44,530 ERROR   SenderThread:8544 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/1t3e085e was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 23:39:48,120 DEBUG   HandlerThread:8544 [handler.py:handle_request():138] handle_request: stop_status
2023-03-21 23:40:04,546 ERROR   SenderThread:8544 [internal_api.py:execute():216] 409 response executing GraphQL.
2023-03-21 23:40:04,546 ERROR   SenderThread:8544 [internal_api.py:execute():217] {"errors":[{"message":"run cringgaard/Sailboat FGVC/1t3e085e was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-21 23:40:08,139 DEBUG   HandlerThread:8544 [handler.py:handle_request():138] handle_request: stop_status
2023-03-21 23:40:11,311 DEBUG   HandlerThread:8544 [handler.py:handle_request():138] handle_request: resume
2023-03-21 23:40:11,311 INFO    HandlerThread:8544 [handler.py:handle_request_resume():687] starting system metrics thread
2023-03-21 23:40:12,339 DEBUG   HandlerThread:8544 [handler.py:handle_request():138] handle_request: poll_exit
2023-03-21 23:40:17,375 DEBUG   HandlerThread:8544 [handler.py:handle_request():138] handle_request: keepalive
